credentials:
  usernames:
    marcelo:
      email: marcelo@example.com
      name: Marcelo
      password: "INSIRA_SENHA_CRIPTOGRAFADA_AQUI"

cookie:
  expiry_days: 30
  key: "autenticacao_usuario"
  name: "login_pdf_app"

preauthorized:
  emails:
    - marcelo@example.com
